### ISSUE TITLE
Found available appointment but didn't actually schedule an appointment.

### ISSUE THREAD

**Issue by eminenceG** [nicktogo/CA-DMV-appointment-scheduler#1]
Hi, 

Thanks for creating this program! I was using it to try to get an appointment, the stdout.log file shows there was available appointment found but I checked the DMV website, I didn't have an appointment. Is this function not supported or I used this program wrongly? 

Output in the stdout.log file: 
```
Finding appointment time...
remote console.log:Appointment time is Friday, August 24, 2018 at 2:20 PM
remote console.log:Office is:  SANTA CLARA

                                                                3665 Flora Vista Ave.

                                                                SANTA CLARA, CA
2018-08-24
Next available: Thu Aug 23 2018 17:00:00 GMT-0700 (PDT)
Today: Mon Aug 13 2018 22:48:05 GMT-0700 (PDT)
10
Done
```

**Comment by eminenceG** [comment]
I found that the numDays must be larger than 14. Why is that necessary?

**Comment by nicktogo** [comment]
Thanks. I guess I mistyped the number. It should be 1.  It is fixed now.

**Comment by eminenceG** [comment]
No problem, and thank you! I changed it to 1 and got a next-day appointment, now I have my driver licence.

**Comment by nicktogo** [comment]
Congrats! 😃
